api:
  nexon:
    maplestorym:
      base_url: ${MAPLESTORYM_BASE_URL}
      header_key: ${MAPLESTORYM_HEADER_KEY}
      header_value: ${MAPLESTORYM_HEADER_VALUE}
      ocid_api_uri: ${MAPLESTORYM_OCID_API_URI}
      basic_api_uri: ${MAPLESTORYM_BASIC_API_URI}
      item_api_uri: ${MAPLESTORYM_ITEM_API_URI}
      stat_api_uri: ${MAPLESTORYM_STAT_API_URI}
      guild_api_uri: ${MAPLESTORYM_GUILD_API_URI}
