name: cd-dev

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy-to-ec2:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Sending build file to NAS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          port: ${{ secrets.NAS_PORT }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          source: "build/libs/*.jar"
          target: "/root/omg/"

      - name: Deploy to EC2 and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          port: ${{ secrets.NAS_PORT }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          script: |
            # 기존에 돌아가고 있던 서비스 종료시키기
            pkill -f 'java.*omg-0.0.1-SNAPSHOT.jar'

            # 새로 배포된 파일 권한 수정
            chmod 755 ${{ secrets.DIRECTORY_PATH}}/omg-0.0.1-SNAPSHOT.jar

            # 새로운 서비스 실행
            nohup java -Dspring.profiles.active=dev -jar ${{ secrets.DIRECTORY_PATH}}/omg-0.0.1-SNAPSHOT.jar > ${{ secrets.DIRECTORY_PATH}}/omg-server.log 2>&1 &
